from typing import Dict

tools = [
    {
        "type": "function",
        "function": {
            "name": "straight",
            "description": "Perform a straight movement",
            "parameters": {
                "type": "object",
                "properties": {
                    "distance": {
                        "type": "number",
                        "minimum": 1,
                        "maximum": 300,
                        "description": "The distance for the straight action in millimeters",
                        "example": 50,
                    },
                    "direction": {
                        "type": "string",
                        "enum": ["forward", "backward"],
                        "description": "The direction for the straight action",
                        "example": "forward",
                    },
                },
                "required": ["distance", "direction"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "turn",
            "description": "Perform a turn action",
            "parameters": {
                "type": "object",
                "properties": {
                    "angle": {
                        "type": "number",
                        "minimum": 1,
                        "maximum": 60,
                        "description": "The angle for the turn action in degrees",
                        "example": 45,
                    },
                    "direction": {
                        "type": "string",
                        "enum": ["left", "right"],
                        "description": "The direction for the turn action",
                        "example": "left",
                    },
                },
                "required": ["angle", "direction"],
            },
        },
    },
]


def user_prompt_tools(
    position: Dict,
    last_command: str,
):
    """
    Generate a user prompt for the robot control agent.
    :param position: The position data.
    :param last_command: The execution result of last command.
    """

    task = """Control the robot to locate and approach a red can in the room, stopping 200mm in front of it, 
    avoiding obstacles."""

    return f"""
            Task: {task}
            Position: {position}
            Last Command: {last_command}
            """


system_prompt_tools = """You are a robot control agent. Generate control signals based on the user prompt, 
which includes the following information: 1. Task: Understand the goal. 2. Tools: Choose appropriate tools for 
controlling the robot. 3. Position: The current position of the robot, with x, y, and phi values. 4. Last Command: 
The information of the last command execution. 5. Camera Image: A QVGA image from the front camera of the robot. 6. 
Lidar Map: A 2D map of the environment generated by the LiDAR sensor."""
