from typing import Dict, List


def user_prompt_text(
    position: Dict,
    last_command: str,
    user_query: str = None,
    experience_states: List[Dict] = None,
):
    """
    Generate a user prompt for the robot control agent.
    :param position: The position data.
    :param last_command: The execution result of last command.
    :param user_query: The user query. TBD
    :param experience_states: The experience states. TBD
    """

    task = """Control the robot to locate and approach a crate in the room, stopping 200mm in front of it, 
    avoiding obstacles."""

    control_method = """
                    - `straight`:
                      - `distance`: 0 < distance < 400 mm
                      - `direction`: forward or backward
                    - `turn`:
                      - `angle`: 0 < angle < 90 degrees
                      - `direction`: left or right
                    """

    response_schema = {
        "perception": "Analyse the position, the camera image, "
        "and LiDAR map, and the last command in plaintext.",
        "planning": "A plan based on the perception in plaintext. The plan need to include control "
        "signals with justifications. At most two control signals.",
        "control": [{"action": "straight", "distance": 50, "direction": "forward"}],
    }

    return f"""
            Task: {task}
            Control Method: {control_method}
            JSON Schema: {response_schema}
            Position: {position}
            Last Command: {last_command}
            """


system_prompt_text = """You are a robot control agent. Generate control signals based on the user prompt, 
which includes the following information: 1. Task: Understand the goal. 2. JSON Schema: Follow the JSON format for 
control signals and justifications. 3. Position: The current position of the robot, with x, y, and phi values. 4. 
Last Command: The information of the last command execution. 5. Camera Image: A QVGA image from the front camera of 
the robot. 6. Lidar Map: A 2D map of the environment generated by the LiDAR sensor."""

# The robot is currently positioned at the center of the LiDAR map (0,0). 0 degrees represents the front of the
# robot. The front-right quadrant spans 0° to 90°, and the left-front quadrant spans 270° to 360°. Identify obstacles
# based on the surrounding dots in the map and plan a path. For objects in the front (300° to 360°, 0° to 60°),
# consider the path with the camera image.
