version: "3"

services:
  eyesim:
    image: eyesim1.5.2:alpha-full-0.0.1
    container_name: eyesim
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .config:/home/eyesim/.config/   
      - .:/home/eyesim/ws/
    environment:
      - DISPLAY
    command: eyesim