version: '1.0'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
#    environment:
#      - NEO4J_AUTH=neo4j/password
#      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins